import re
import os
import json

with open("the-great-christmas-disaster-book-page.html", "r", encoding="utf-8") as f:
    template = f.read()

# I will store the data in an array of dicts.
books = [
    {
        "id": "1", "tag": "Whispering Falls #1", "title": "Inheriting Love", "file": "inheriting-love-book-page.html", "cover": "1c-Inheriting Love copy.jpg", "link": "https://amzn.to/4lAAtfn",
        "blurb": "<h2>Small-town girl meets grumpy big city boy, and those two do not see eye-to-eye.</h2><p>Whispering Falls is more than just a postcard-perfect town with a rich history. It's where unexpected encounters can lead to life-changing sparks. Danika Walters, the life of the local history scene, is all about community vibes and keeping the town's old-school charm alive. She's got this knack for making everyone feel like they're home.</p><p>Steven Hillman is a graphic designer straight out of the NYC hustle. Life throws him a curveball, however, when he inherits his uncle's rundown home in Whispering Falls. He's a grumpy loner when it comes to relationships, which is pretty much the opposite of Danika's outgoing personality.</p><p>Having to take time off from his job in New York for a small town puts his love for going it alone to the test when he meets the intriguing Danika.</p><p>The two are thrown together by fate with a side of fresh chemistry. They're both trying to do something great with the old house, but their plans are as mismatched as their personalities, making Steven rethink his lone-wolf ways and lighting up some of Danika's own pushed-aside dreams.</p><p class=\"book-meta\">INHERITING LOVE dives into a down-to-earth love that unfolds in the laid-back lanes of Whispering Falls, where falling leaves and falling in love remind us that the best things we inherit aren't just houses or antiques, but the chance to find true love.</p>"
    },
    {
        "id": "2", "tag": "Whispering Falls #2", "title": "Summertime Sonata", "file": "summertime-sonata-book-page.html", "cover": "2c-Summertime Sonata copy.jpg", "link": "https://amzn.to/4lD8Ull",
        "blurb": "<h2>A love both sweet and deep blooms in Whispering Falls, where dreams and desires dance to the rhythm of Anna’s violin.</h2><p>Anna Avery, a celebrated violinist, returns to her New England hometown of Whispering Falls to headline the Summer Music Festival, a heartfelt nod to her late mother. It's here that she crosses paths again with Michael Reed, her former love. They had shared two years of deep connection before Anna's pursuit of her dreams led her away, leaving their relationship behind.</p><p>Now, as they reunite, their past chemistry quickly rekindles, weaving together memories and the promise of a new beginning. As they collaborate for the festival, their partnership reawakens a romance that feels both familiar and fresh, set against the rejuvenating backdrop of summer and the melodies of Anna's violin.</p><p>However, the harmony of their rekindled love faces a challenge. Anna is offered a life-changing opportunity with the National Symphony Orchestra, a dream that once pulled them apart. Faced with the glamour of a celebrated career or the depth of love and community in Whispering Falls, Anna stands at a crossroads once more.</p><p class=\"book-meta\">Will Anna choose the bright lights of the concert stage, or will she opt for the enduring warmth of love and a second chance with Michael?</p>"
    },
    {
        "id": "3", "tag": "Whispering Falls #3", "title": "Rebuilding Hearts", "file": "rebuilding-hearts-book-page.html", "cover": "3c-Rebuilding Hearts copy.jpg", "link": "https://amzn.to/4sXAyMA",
        "blurb": "<h2>A second chance at love, a meddling ex-boyfriend, and an adorable 8-year-old daughter make this love story intriguing and emotionally satisfying.</h2><p>Jack Delaney was Sophie Turner’s anchor during their high school days in Whispering Falls. Thirteen years have passed since Jack left their idyllic town to chase his dreams, while Sophie chose to stay and express her art through pottery.</p><p>Fresh out of college with a construction degree, Jack's life took a sharp turn when he fell in love and quickly became a single dad—a role he had not anticipated.</p><p>A twist of fate brings Jack back to Whispering Falls to help his father develop a business park. Being home leads to an unexpected reunion with Sophie, and reconnecting with her stirs up old memories. But Jack's heart is guarded.</p><p>Complications arise when she takes on a job for her ex-boyfriend and he starts to hangs around her too much. When tragedy strikes, Jack and Sophie must navigate through their complex past and the growing feelings that cannot be ignored. Yet, a web of mistrust and conflicting interests looms over them, risking the future of Sophie's business and their rekindled connection.</p><p class=\"book-meta\">Set in charming Whispering Falls, Massachusetts—a town with a feel-good sense of community that will make you want to visit time and again.</p>"
    },
    {
        "id": "4", "tag": "Whispering Falls #4", "title": "Briefs and Bouquets", "file": "briefs-and-bouquets-book-page.html", "cover": "4c-Briefs and Bouquets copy.jpg", "link": "https://amzn.to/4sTcgDc",
        "blurb": "<h2>Love or Law? A Chicago lawyer's heart tangles with a laid-back charmer in the eye of the storm...</h2><p>In the bustling city of Chicago, Willow Davies is a driven lawyer on the cusp of achieving her long-awaited partnership. But when her younger sister's wedding calls her to the quaint town of Whispering Falls, Massachusetts, Willow finds herself torn between her career ambitions and the pull of family obligations.</p><p>As the Maid of Honor, Willow is unexpectedly paired with the charming and laid-back Best Man, Rowan McCarthy. Through a whirlwind of wedding festivities and a serendipitous scavenger hunt, Willow begins to question her structured approach to life and the dreams she's been chasing.</p><p>But when a hurricane strikes, trapping Willow in Whispering Falls, she finds herself seeking shelter in Rowan's home. As the storm rages outside, Willow must navigate the tempest within her own heart, confronting the growing attraction to Rowan and the doubts about her chosen path.</p><p class=\"book-meta\">Will she choose the life she's always planned, or will she embrace the unexpected love that's been brewing amidst the storm?</p>"
    },
    {
        "id": "5", "tag": "Whispering Falls #5", "title": "Decorating With Love", "file": "decorating-with-love-book-page.html", "cover": "5c-Decorating With Love copy.jpg", "link": "https://amzn.to/4cQ1JUK",
        "blurb": "<h2>In the whisper of love's design, can a faux engagement lead to true romance?</h2><p>In the cozy town of Whispering Falls, Massachusetts, Joy Fletcher's dreams and designs are the heart of her struggling interior design firm. When the opportunity to decorate the home of the town's new doctor arises, Joy sees it as her chance to prove her talent and secure her business' future.</p><p>Dr. Cameron Browning leaves the hustle of Boston for a quieter life in Whispering Falls in order to provide a stable home for his son, Sam. Committed to protecting him from any more loss, Cameron has kept his relationships light and his heart guarded—until a blast from the past threatens to unravel the life he's carefully built.</p><p>Brittany Welling's unexpected arrival in Whispering Falls, aiming to rekindle her relationship with Cameron, prompts a panicked lie from him that he's engaged to Joy Fletcher who reluctantly agrees to the charade to save her crucial commission.</p><p>But as the pretend engagement becomes public gossip, Cameron and Joy find themselves entangled in a web of deception, community scrutiny, and unexpected feelings.</p><p class=\"book-meta\">Set in charming Whispering Falls, Massachusetts—a town with a feel-good sense of community that will make you want to visit time and again.</p>"
    },
    {
        "id": "6", "tag": "Whispering Falls #6", "title": "Mistletoe and Heartstrings", "file": "mistletoe-and-heartstrings-book-page.html", "cover": "6c-Mistletoe and Heartstrings copy.jpg", "link": "https://amzn.to/4df4m2L",
        "blurb": "<h2>In Whispering Falls, love and mystery tangle together under the mistletoe.</h2><p>When New York Times bestselling author, Donovan Butler, retreats to the cozy town of Whispering Falls to escape his writer's block and a broken heart, he expects peace and quiet—not a meddling café owner with a penchant for solving mysteries.</p><p>Tina Wilson, the spirited owner of the Whispering Willow Café, has her hands full with a secret admirer and a thriving café to run. As Christmas approaches, Donovan and Tina find themselves tangled in a web of letters, laughter, and unexpected love.</p><p>Can the pull of heartstrings be enough to turn Donovan's winter retreat into a forever kind of thing?</p><p class=\"book-meta\">Prepare for a delightful mix of mistletoe, mystery, and romance that will leave your heart glowing this holiday season!</p>"
    },
    {
        "id": "7", "tag": "Whispering Falls #7", "title": "Runaway Romance", "file": "runaway-romance-book-page.html", "cover": "7c-Runaway Romance copy.jpg", "link": "https://amzn.to/4se7kZP",
        "blurb": "<h2>Lost in the search, found in love.</h2><p>In the charming town of Whispering Falls, wedding planner Ivy Jennings is all set to create the perfect day for her good friend—until the groom, Mark, mysteriously disappears just days before the wedding. With the clock ticking, Ivy teams up with the best man, Connor Sterling, a handsome but emotionally guarded architect who’s as skeptical about love as he is about finding Mark in time.</p><p>As they follow a trail of unexpected clues, Ivy and Connor find themselves drawn into a journey that’s as much about discovering each other as it is about solving the mystery. Against the backdrop of quaint streets and cozy cafes, they begin to unravel their own fears and defenses, realizing that sometimes love shows up when you least expect it.</p><p class=\"book-meta\">Will Ivy and Connor find Mark and save the wedding? Or will they discover that the real adventure lies in opening their hearts to the possibility of love?</p>"
    },
    {
        "id": "8", "tag": "Whispering Falls #8", "title": "Matchmaker's Dilemma", "file": "matchmakers-dilemma-book-page.html", "cover": "8c-Matchmaker's Dilemma copy.jpg", "link": "https://amzn.to/4cWhUzQ",
        "blurb": "<h2>When love is all about the perfect match, what happens when you become the one who’s off-limits?</h2><p>Shannon Cook is a matchmaker with a rule: she doesn’t date her clients. Ever. With her one-of-a-kind algorithm and a reputation as unshakable as her resolve, she’s made a business out of finding everyone else’s perfect match in the picturesque town of Whispering Falls. Her own love life? Well, let’s just say it’s a sacrifice she’s more than willing to make.</p><p>Enter Tyler Scott—a charming, commitment-phobic playboy who’d rather be anywhere else than in Shannon’s office. But thanks to his father’s ultimatum (find a fiancée or kiss the family business goodbye), Tyler has no choice but to use Shannon’s matchmaking services. Trouble is, every woman Shannon sends his way is a flop. Miserably. And no one is more surprised than Shannon when Tyler’s attention starts shifting from the dates...to her.</p><p>Tyler may be a disaster when it comes to romance, but he’s good at one thing—getting what he wants. And now, what he wants is Shannon. The only problem? Falling for a client could ruin everything Shannon’s worked for. But as mismatches, witty banter, and awkwardly adorable encounters pile up, she starts wondering if maybe, just maybe, some rules were made to be broken.</p><p class=\"book-meta\">Matchmaker’s Dilemma is a swoon-worthy romance about finding love where you least expect it—and realizing that sometimes, the perfect match is the one that defies all your algorithms.</p>"
    },
    {
        "id": "9", "tag": "Whispering Falls #9", "title": "Snowflakes and Miracles", "file": "snowflakes-and-miracles-book-page.html", "cover": "9c-Snowflakes and Miracles copy.jpg", "link": "https://amzn.to/4dvO9Gh",
        "blurb": "<h2>When ambition meets tradition in the snowy hills of Whispering Falls, sparks fly and hearts begin to thaw.</h2><p>Damon Andrews is determined to save his family’s ski lodge, a rustic gem nestled in the snowy hills outside Whispering Falls, Massachusetts. With winter fast approaching, he’s banking on the season to bring in much-needed revenue—if only his father would stop pushing to sell.</p><p>Megan Cassidy has one shot at landing her dream promotion: convincing the Andrews family to sell their struggling lodge to her high-end Boston firm. But her first meeting with Damon proves anything but smooth. When sparks fly, Megan is drawn to the fiercely passionate man who refuses to let go of his family’s legacy.</p><p class=\"book-meta\">As the holiday season weaves its magic, Megan and Damon must decide whether love can bridge the gap between ambition and tradition—or if their hearts are destined to remain as cold as the falling snow.</p>"
    },
    {
        "id": "10", "tag": "Whispering Falls #10", "title": "Code Red for Love", "file": "code-red-for-love-book-page.html", "cover": "10c-Code Red for Love copy.jpg", "link": "https://amzn.to/4d1A6Z3",
        "blurb": "<h2>Can two tech rivals debug their hearts and find true love?</h2><p>When Luke Hopkins, the reserved tech genius behind Happily Matched, heads to Boston for the year’s biggest tech conference, he’s ready to talk code—not love. But his plans are derailed by Paige Miller, a bold, no-nonsense entrepreneur launching her rival matchmaking app, HeartSync. Their first meeting is less of a meet-cute and more of a tech catastrophe, complete with stolen spotlights and scathing one-liners.</p><p>But when mysterious glitches start sabotaging their apps, Luke and Paige are forced into an uneasy alliance to uncover the culprit. Between late-night coding marathons, competitive banter, and sparks that aren’t entirely from faulty wiring, Luke realizes there’s more to Paige than just her flashy algorithms. And Paige? She might just be falling for the sweet, socially awkward guy who’s not as clueless about love as he seems.</p><p class=\"book-meta\">In a world of ones and zeros, will Luke and Paige find their perfect match—or will their love story crash before it even begins?</p>"
    },
    {
        "id": "11", "tag": "Whispering Falls #11", "title": "Hearts in Hiding", "file": "hearts-in-hiding-book-page.html", "cover": "11c-Hearts in HIding copy.jpg", "link": "https://amzn.to/3Prhojx",
        "blurb": "<h2>A brooding journalist and a curious novelist confront the shadows of yesteryear.</h2><p>Sage Collins, a bestselling author who has settled in Whispering Falls for a quieter life, finds her focus shattered when Gabriel Cross moves across the street into the Morgan estate, an imposing mansion with a tarnished reputation.</p><p>Gabriel, a former investigative journalist with secrets of his own, intends to restore the estate. He is unaware of its dark history, which is shrouded in murder, intrigue, and whispered tales of hidden treasures.</p><p>Determined to uncover the mansion's secrets—and hopefully find inspiration—Sage persuades Gabe to grant her access. Together, they discover a forgotten diary in the attic that helps to unravel a web of mysteries that intertwine with their own lives.</p><p class=\"book-meta\">As they delve deeper into the past, their partnership blossoms into something neither expected.</p>"
    },
    {
        "id": "12", "tag": "Whispering Falls #12", "title": "Blueprint of the Heart", "file": "blueprint-of-the-heart-book-page.html", "cover": "12-WF Blueprint of the Heart copy.jpg", "link": "https://amzn.to/40Hp2ZD",
        "blurb": "<h2>Sometimes love needs a new foundation.</h2><p>When Boston architect Charlie Reynolds returns to Whispering Falls to restore a crumbling Victorian into a pottery studio, she's focused on one thing: proving she can rebuild her career on her own terms. She doesn’t expect to clash with rugged, small-town contractor Rider Summers—especially not over bricks, budgets, or bakery choices.</p><p>But between floured cheeks, snowstorm strolls, and Sunday sourdough, something starts to shift. As walls come down and sparks begin to fly, Charlie must decide if the future she’s designing still leads back to the city—or if the real blueprint of her heart has been unfolding here all along.</p>"
    },
    {
        "id": "13", "tag": "Whispering Falls #13", "title": "Borrowed Hearts", "file": "borrowed-hearts-book-page.html", "cover": "13-WF Borrowed Hearts copy.jpg", "link": "https://amzn.to/47Em9wq",
        "blurb": "<h2>Fake boyfriend needed. Real feelings included. Cat-induced chaos guaranteed.</h2><p>When Heather's high school reunion looms, and her ex is bringing his perfect new fiancée, she does what any rational woman would do: panic.</p><p>Her solution? Convince her ridiculously attractive neighbor to be her fake boyfriend for the weekend. What could go wrong? Well, apparently everything—starting with her sociopathic cat Vincent, who seems determined to sabotage every fake romantic moment.</p><p class=\"book-meta\">But the real problem isn't Vincent's reign of domestic terror. It's that somewhere between the practice dates and the pretend hand-holding, Heather's fake feelings are starting to feel dangerously real.</p>"
    },
    {
        "id": "BS1", "tag": "Books 1-3", "title": "Whispering Falls Box Set 1-3", "file": "whispering-falls-box-set-1-3-book-page.html", "cover": "BS 1-3.jpg", "link": "https://amzn.to/47JCuQv",
        "blurb": "<h2>Escape to Whispering Falls with this heartwarming collection of sweet romances.</h2><p>Where love blooms in unexpected ways, second chances linger in the air, and small-town charm is always in season. This boxed set includes the first three full-length novels in the Whispering Falls Sweet Romance series—perfect for fans of cozy towns, feel-good love stories, and emotionally satisfying journeys.</p><p><strong>Inheriting Love:</strong> When grumpy New York graphic designer Steven Hillman inherits a rundown house, the last thing he expects is Danika Walters—Miss Small-Town Sunshine herself.</p><p><strong>Summertime Sonata:</strong> World-renowned violinist Anna Avery returns home to honor her late mother—and ends up face-to-face with the man she once loved.</p><p><strong>Rebuilding Hearts:</strong> Jack Delaney never expected to return to Whispering Falls—or to raise his daughter alone. But when he reconnects with Sophie Turner, the girl he once loved, old feelings resurface fast.</p><p class=\"book-meta\">If you enjoy small-town settings, layered characters, and sweet, slow-burn romances with plenty of heart, you’ll love this collection of Whispering Falls stories.</p>"
    },
    {
        "id": "BS2", "tag": "Books 4-6", "title": "Whispering Falls Box Set 4-6", "file": "whispering-falls-box-set-4-6-book-page.html", "cover": "BS 4-6.jpg", "link": "https://amzn.to/41jC5Ax",
        "blurb": "<h2>Return to Whispering Falls with this delightful collection of sweet romances filled with holiday charm.</h2><p>This boxed set includes books 4–6 in the beloved Whispering Falls Sweet Romance series—perfect for readers who adore emotional depth, charming townsfolk, and happily-ever-afters set against the backdrop of love and laughter.</p><p><strong>Briefs and Bouquets:</strong> Ambitious Chicago lawyer Willow Davies only plans to visit Whispering Falls long enough to help with her sister’s wedding. But a surprise pairing—and an unexpected hurricane—leave her rethinking everything.</p><p><strong>Decorating with Love:</strong> Interior designer Joy Fletcher is determined to save her struggling business. When her client invents a fake engagement with Joy, what starts as a harmless ruse turns into something deeper.</p><p><strong>Mistletoe and Heartstrings:</strong> Bestselling author Donovan Butler needs a break from the spotlight. Whispering Falls seems perfect until he meets Tina Wilson, a café owner with a secret admirer.</p><p class=\"book-meta\">From festive holidays to stolen kisses and unexpected twists, these heartfelt love stories will warm your heart.</p>"
    },
    {
        "id": "BS3", "tag": "Books 7-9", "title": "Whispering Falls Box Set 7-9", "file": "whispering-falls-box-set-7-9-book-page.html", "cover": "BS 7-9.jpg", "link": "https://amzn.to/478up7R",
        "blurb": "<h2>Fall in love all over again in Whispering Falls with three more heartwarming romances.</h2><p>This boxed set includes books 7–9 of the Whispering Falls Sweet Romance series—perfect for readers who adore cozy small towns, swoon-worthy heroes, and slow-burn love stories with emotional depth and just the right dash of humor.</p><p><strong>Runaway Romance:</strong> Wedding planner Ivy Jennings has everything under control—until the groom disappears just days before the ceremony. Enter Connor Sterling, the brooding best man and a reluctant partner in the search.</p><p><strong>Matchmaker’s Dilemma:</strong> Shannon Cook has one rule: never date a client. But when charming and frustrating Tyler Scott is forced into her matchmaking service, sparks fly and rules blur.</p><p><strong>Snowflakes and Miracles:</strong> Megan Cassidy’s big-city ambition collides with Damon Andrews’ small-town loyalty when she tries to convince him to sell his family’s ski lodge.</p><p class=\"book-meta\">From missing grooms to fake fiancés and holiday miracles, this sweet and satisfying collection will sweep you into the warmth of Whispering Falls.</p>"
    },
    {
        "id": "BS4", "tag": "Books 10-12", "title": "Whispering Falls Box Set 10-12", "file": "whispering-falls-box-set-10-12-book-page.html", "cover": "BS 10-12.jpg", "link": None,
        "blurb": "<h2>Return to Whispering Falls for three more unforgettable romances!</h2><p>This sweet collection brings you back to the cozy streets and charming locals of Whispering Falls, where love is always in the air.</p><p class=\"book-meta\">Available soon!</p>"
    }
]

for b in books:
    html = template
    html = html.replace("The Great Christmas Disaster Book Page", b["title"] + " Book Page")
    html = html.replace("Love Only #1", b["tag"])
    html = html.replace("1-LO The Great Christmas Disaster.jpg", b["cover"])
    html = html.replace("The Great Christmas Disaster", b["title"])
    html = html.replace("the-great-christmas-disaster-book-page.html", b["file"])
    
    # Replace Button
    if b["link"]:
        btn_replacement = f"<a href=\"{b['link']}\" target=\"_blank\" class=\"btn btn-primary\" rel=\"noopener\">Buy on Amazon </a>"
    else:
        btn_replacement = "<button class=\"btn btn-primary\" style=\"cursor:not-allowed; opacity:0.7;\" disabled>COMING SOON</button>"
        
    html = html.replace("<a href=\"https://amzn.to/476J978\" target=\"_blank\" class=\"btn btn-primary\" rel=\"noopener\">Buy on Amazon </a>", btn_replacement)
    
    # Replace blurb
    html = re.sub(r"<div id=\"blurb\" class=\"book-blurb\">.*?</div></div></section>", 
                  "<div id=\"blurb\" class=\"book-blurb\">" + b["blurb"] + "</div></div></section>", html, flags=re.DOTALL)
                  
    with open(b["file"], "w", encoding="utf-8") as f:
        f.write(html)
        
print("Successfully generated Whispering Falls book pages.")
